apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-client
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    app: {{ .Release.Name }}-client
