replicaCount: 1

image:
  repository: <your-dockerhub-username>/server
  pullPolicy: Always
  tag: latest

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: server.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
